// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMAeGVA8xcwyDSAw2obbEj8YCeP9C1Shc',
    appId: '1:695069693791:web:e80cd9d637565ecb9808ea',
    messagingSenderId: '695069693791',
    projectId: 'flutternelsonmandelasosabin',
    authDomain: 'flutternelsonmandelasosabin.firebaseapp.com',
    storageBucket: 'flutternelsonmandelasosabin.appspot.com',
    measurementId: 'G-H5MJ91KHYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7Tkv1lZi-BmKZBKN9vgoupoAMhFK3gnE',
    appId: '1:695069693791:android:209161524d444fd69808ea',
    messagingSenderId: '695069693791',
    projectId: 'flutternelsonmandelasosabin',
    storageBucket: 'flutternelsonmandelasosabin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcDSg6Fq23xC9X8u1WNq1B2m9xqz2W5cU',
    appId: '1:695069693791:ios:1e3a97a790cce2b89808ea',
    messagingSenderId: '695069693791',
    projectId: 'flutternelsonmandelasosabin',
    storageBucket: 'flutternelsonmandelasosabin.appspot.com',
    iosBundleId: 'com.example.newLoginScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcDSg6Fq23xC9X8u1WNq1B2m9xqz2W5cU',
    appId: '1:695069693791:ios:1e3a97a790cce2b89808ea',
    messagingSenderId: '695069693791',
    projectId: 'flutternelsonmandelasosabin',
    storageBucket: 'flutternelsonmandelasosabin.appspot.com',
    iosBundleId: 'com.example.newLoginScreen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMAeGVA8xcwyDSAw2obbEj8YCeP9C1Shc',
    appId: '1:695069693791:web:c3314a1036ab67ec9808ea',
    messagingSenderId: '695069693791',
    projectId: 'flutternelsonmandelasosabin',
    authDomain: 'flutternelsonmandelasosabin.firebaseapp.com',
    storageBucket: 'flutternelsonmandelasosabin.appspot.com',
    measurementId: 'G-XMVTEHX7ZJ',
  );
}
